services:
  app:
    build:
      context: .
    depends_on:
      - database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 3000:3000

  database:
    image: postgres:latest
    volumes: 
     - database:/data/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_USER: admin

volumes:
  database: