#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --git-dir)
echo "Installing hooks..."
# this command creates symlink to our pre-commit script
ln -sfn ../../scripts/pre-commit $GIT_DIR/hooks/pre-commit
ln -sfn ../../scripts/pre-push $GIT_DIR/hooks/pre-push

chmod +x $GIT_DIR/hooks/pre-commit
chmod +x $GIT_DIR/hooks/pre-push

echo "Done!"