#!/usr/bin/env bash
echo "stashing unstaged changes"
git stash --keep-index
echo "Running pre-commit hook"
./scripts/run-rubocop

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Code must be clean before commiting. Run rubocop for linting."
 exit 1
else
 echo "Adding rubocop changes to your commit"
 git add -u
fi
echo "unstashing changes..."
git stash pop